version: '3.8'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
    ports:
      - "5900:5432"
  redis:
    image: redis:alpine3.17
    ports:
      - "6379:6379"
