version: '3.8'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: gary
      POSTGRES_PASSWORD: w1shl1st
      POSTGRES_DB: gary_db
    ports:
      - "5932:5432"
  # valkey:
  #   image: valkey/valkey:7-alpine3.19
  #   ports:
  #     - "6379:6379"
