version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine3.17
    ports:
      - "6379:6379"
