# Generated by Django 4.0 on 2021-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifter', '0002_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='http_origin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
