# Generated by Django 4.1.2 on 2023-03-09 04:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifter", "0004_alter_groupinvitation_verification_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claim",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="groupinvitation",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
    ]
