# Generated by Django 4.1.2 on 2023-12-17 02:04

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Wishlist = apps.get_model("gifter", "Wishlist")
    for wishlist in Wishlist.objects.all():
        wishlist.groups.add(wishlist.group)
        wishlist.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gifter", "0005_alter_claim_options_alter_groupinvitation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="groups",
            field=models.ManyToManyField(related_name="wishlists", to="auth.group"),
        ),
        migrations.RunPython(
            code=forwards_func,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
