# Generated by Django 4.1.2 on 2023-12-17 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gifter", "0006_wishlist_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="group",
        ),
    ]
