#!/usr/bin/env bash

./manage.py collectstatic --no-input --clear
./manage.py migrate

# To specify number of threads, define ASGI_THREADS
# By default, asgi uses <num CPUs> * 5
daphne --bind 0.0.0.0 --port 8000 gary.asgi:application