name: Tests

env:
  CI=1

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.3.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
          cache: 'poetry'
      - name: Install deps
        run: |
          poetry install
      - name: Run Database & Redis
        run: |
          docker-compose up -d
      - name: Unit Tests
        run: poetry run python ./manage.py test
